labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: If you don't have a reproduction link, please choose a different category.
  - type: textarea
    attributes:
      label: Bug Description
      description: hoge
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction Link
      description: hoge.
    validations:
      required: true
