contact_links:
  - name: test
    url: https://github.com/hkr-hr/jotai/discussions/new?category=test
    about: Please post bug reports here.
  - name: Questions
    url: https://github.com/pmndrs/jotai/discussions/new?category=q-a
    about: Please post questions here.
  - name: Other Discussions
    url: https://github.com/pmndrs/jotai/discussions/new/choose
    about: Please post ideas and general discussions here.
