contact_links:
  - name: バグレポート
    url: https://github.com/hkr-hr/jotai/discussions/new?category=%E3%83%90%E3%82%B0%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88
    about: Please post bug reports here.
  - name: Questions
    url: https://github.com/pmndrs/jotai/discussions/new?category=q-a
    about: Please post questions here.
  - name: Other Discussions
    url: https://github.com/pmndrs/jotai/discussions/new/choose
    about: Please post ideas and general discussions here.
